version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosec
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
  settings:
    gosec:
      excludes:
        - G104
    govet:
      enable-all: true
      disable:
        - fieldalignment
